#pragma once

// from glfw3.h
#define RUNNING_MOUSE_BUTTON_1         0
#define RUNNING_MOUSE_BUTTON_2         1
#define RUNNING_MOUSE_BUTTON_3         2
#define RUNNING_MOUSE_BUTTON_4         3
#define RUNNING_MOUSE_BUTTON_5         4
#define RUNNING_MOUSE_BUTTON_6         5
#define RUNNING_MOUSE_BUTTON_7         6
#define RUNNING_MOUSE_BUTTON_8         7
#define RUNNING_MOUSE_BUTTON_LAST      RUNNING_MOUSE_BUTTON_8
#define RUNNING_MOUSE_BUTTON_LEFT      RUNNING_MOUSE_BUTTON_1
#define RUNNING_MOUSE_BUTTON_RIGHT     RUNNING_MOUSE_BUTTON_2
#define RUNNING_MOUSE_BUTTON_MIDDLE    RUNNING_MOUSE_BUTTON_3
